name: Upload and Download Artifact

on:
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - run: |
          echo "Build Successful" > output.txt

      - uses: actions/upload-artifact@v4
        with:
          name: build-output
          path: output.txt

  consume:
    needs: build

    runs-on: ubuntu-latest

    steps:
      - uses: actions/download-artifact@v4
        with:
          name: build-output

      - run: |
          cat output.txt